window.HOURTIME = window.HOURTIME || {};
HOURTIME.PROFILE_COPY={
subi:{label:"LE POMPIER DU TEMPS",description:"Vos journées sont surtout pilotées par les urgences et les imprévus du moment.",strength:"Vous réagissez vite et savez gérer les situations urgentes.",risk:"Les priorités importantes sont souvent repoussées par l'urgence du quotidien.",lever:"Installer 1 à 2 priorités non négociables par jour avec un créneau protégé."},
disperse:{label:"LE ZAPPEUR DU TEMPS",description:"Votre attention est partagée entre trop de sujets, ce qui fragmente vos avancées.",strength:"Vous êtes adaptable, curieux et capable de passer d'un sujet à l'autre.",risk:"La dispersion use l'énergie et ralentit la finalisation des tâches importantes.",lever:"Limiter le nombre de sujets ouverts et terminer avant de relancer."},
sacrifie:{label:"LE DONNEUR DE TEMPS",description:"Vous consacrez beaucoup de temps aux autres, parfois au détriment de vos propres priorités.",strength:"Vous êtes fiable, disponible et engagé pour les autres.",risk:"Vos besoins, votre récupération et vos projets personnels passent après.",lever:"Poser des limites simples et réserver du temps pour vous en premier."},
controle:{label:"LE CONTRÔLEUR DU TEMPS",description:"Vous êtes structuré et organisé, avec une bonne maîtrise de vos journées.",strength:"Rigueur, anticipation et capacité à faire avancer les priorités.",risk:"La surcharge, la rigidité ou le perfectionnisme peuvent reprendre de la place.",lever:"Garder de la marge et viser l'efficacité utile plutôt que le contrôle total."},
aligne:{label:"L’ARCHITECTE DU TEMPS",description:"Votre temps est globalement aligné avec vos priorités et votre équilibre de vie.",strength:"Vous combinez clarté, organisation, protection et passage à l'action.",risk:"Chercher à sur-optimiser ce qui fonctionne déjà et perdre en souplesse.",lever:"Consolider vos routines clés et corriger seulement les fragilités restantes."}
};
HOURTIME.assignProfile=function(answers,result){const m=result.mechanisms,t=Object.fromEntries(result.thieves.map(x=>[x.id,x.score])),index=result.index;if(index>=82&&Object.values(m).every(v=>v>=70)&&result.thieves.every(x=>x.score<55)&&Number(answers[25])>=4&&Number(answers[28])>=4)return{primary:"aligne",secondary:null,scores:{aligne:100}};const scores={subi:HOURTIME.clamp(.35*(t.urgences||0)+.25*(t.surcharge||0)+.20*(100-m.organiser)+.20*(100-m.proteger)),disperse:HOURTIME.clamp(.45*(t.dispersion||0)+.20*(t.procrastination||0)+.15*(t.interruptions||0)+.20*(100-m.agir)),sacrifie:HOURTIME.clamp(.45*(t.autres||0)+.20*(t.energie||0)+.20*(100-m.proteger)+.15*HOURTIME.deficit(answers[19])),controle:HOURTIME.clamp(.35*m.organiser+.30*(t.perfectionnisme||0)+.20*(t.surcharge||0)+.15*HOURTIME.deficit(answers[11]))};const eligible=["subi","disperse","sacrifie"];const controlEligible=m.organiser>=65&&((t.perfectionnisme||0)>=50||Number(answers[11])<=3);if(controlEligible)eligible.push("controle");const ranked=eligible.map(k=>[k,scores[k]]).sort((a,b)=>b[1]-a[1]);const primary=ranked[0][0];const secondary=ranked[1]&&ranked[0][1]-ranked[1][1]<=10?ranked[1][0]:null;return{primary,secondary,scores}};
