window.HOURTIME = window.HOURTIME || {};
HOURTIME.PROFILE_COPY={
subi:{label:"Le Temps subi",description:"Vos journées sont souvent déterminées par les urgences, les sollicitations et ce qui arrive au dernier moment.",strength:"Vous savez souvent vous adapter rapidement à ce qui se présente.",risk:"Vos propres priorités passent après les demandes du quotidien.",lever:"Reprendre de la marge et choisir quelques priorités non négociables."},
disperse:{label:"Le Temps dispersé",description:"Votre attention se partage entre trop de sujets, ce qui donne l'impression d'être occupé sans toujours avancer comme vous le souhaitez.",strength:"Curiosité, souplesse et capacité à passer rapidement d'un sujet à l'autre.",risk:"Commencer beaucoup, terminer peu et perdre de l'énergie dans les changements de contexte.",lever:"Réduire le nombre de choses ouvertes en même temps et terminer avant d'ajouter."},
sacrifie:{label:"Le Temps sacrifié",description:"Vous donnez beaucoup de votre temps aux autres, aux responsabilités ou aux demandes extérieures, parfois au détriment de vos propres besoins.",strength:"Disponibilité, générosité et sens des responsabilités.",risk:"Ne plus préserver assez de temps pour vous, vos proches, votre repos ou vos projets.",lever:"Créer des limites simples et réserver du temps personnel avant que tout l'agenda soit rempli."},
controle:{label:"Le Temps contrôlé",description:"Vous aimez structurer, prévoir et garder la maîtrise de vos journées. Votre organisation est une force, mais elle peut parfois devenir trop rigide.",strength:"Rigueur, anticipation et stabilité.",risk:"Chercher à tout contrôler, sur-planifier ou laisser trop peu de place à l'imprévu et au plaisir.",lever:"Préserver volontairement de la marge et accepter qu'une journée réussie ne soit pas une journée remplie."},
aligne:{label:"Le Temps aligné",description:"Votre temps reflète globalement vos priorités, vos valeurs et la vie que vous souhaitez construire.",strength:"Cohérence entre choix, organisation, action et récupération.",risk:"Transformer l'optimisation en nouvelle contrainte alors que l'essentiel fonctionne déjà.",lever:"Conserver les bonnes pratiques et concentrer vos efforts uniquement sur les quelques fragilités restantes."}
};
HOURTIME.assignProfile=function(answers,result){const m=result.mechanisms,t=Object.fromEntries(result.thieves.map(x=>[x.id,x.score])),index=result.index;if(index>=82&&Object.values(m).every(v=>v>=70)&&result.thieves.every(x=>x.score<55)&&Number(answers[25])>=4&&Number(answers[28])>=4)return{primary:"aligne",secondary:null,scores:{aligne:100}};const scores={subi:HOURTIME.clamp(.35*(t.urgences||0)+.25*(t.surcharge||0)+.20*(100-m.organiser)+.20*(100-m.proteger)),disperse:HOURTIME.clamp(.45*(t.dispersion||0)+.20*(t.procrastination||0)+.15*(t.interruptions||0)+.20*(100-m.agir)),sacrifie:HOURTIME.clamp(.45*(t.autres||0)+.20*(t.energie||0)+.20*(100-m.proteger)+.15*HOURTIME.deficit(answers[19])),controle:HOURTIME.clamp(.35*m.organiser+.30*(t.perfectionnisme||0)+.20*(t.surcharge||0)+.15*HOURTIME.deficit(answers[11]))};const eligible=["subi","disperse","sacrifie"];const controlEligible=m.organiser>=65&&((t.perfectionnisme||0)>=50||Number(answers[11])<=3);if(controlEligible)eligible.push("controle");const ranked=eligible.map(k=>[k,scores[k]]).sort((a,b)=>b[1]-a[1]);const primary=ranked[0][0];const secondary=ranked[1]&&ranked[0][1]-ranked[1][1]<=10?ranked[1][0]:null;return{primary,secondary,scores}};
